### ISSUE TITLE
在8.1模拟器上运行点击两次pikerView会崩溃

### ISSUE THREAD

**Issue by Dongjian413** [KenmuHuang/KMDatePicker#1]
是点击不是滑动，点两次不同的月份或者日期就会崩溃

**Comment by KenmuHuang** [comment]
我这边模拟器操作没出现崩溃问题，具体的报错信息？是否代码进一步自定义修改了？ @HotSummerS

**Comment by Dongjian413** [comment]
对，是添加了一个显示效果，问题解决了，原因是我加了一个全局断点，，
