### ISSUE TITLE
有BUG：设置时间范围的无法定位到当前时间

### ISSUE THREAD

**Issue by jun-hui** [KenmuHuang/KMDatePicker#2]
如题，选择当前日期时间时，自动滚动到了起始日期时间

**Comment by KenmuHuang** [comment]
设置时间限制范围需要保证当前时间在范围区间内，Demo 中是没问题的

**Comment by jun-hui** [comment]
我的意思是，起始日期任意，结束日期为今天，滚不到今天的日期，自动滚动到了起始日期时间，不信你试试

**Comment by KenmuHuang** [comment]
请设置 defaultLimitedDate 属性值解决此问题（默认限制时间；默认值为最小限制时间，当选择时间不在指定范围，就滚动到此默认限制时间）
